name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set Image Tag
      id: vars
      run: echo "tag=strapi-${{ github.sha }}" >> $GITHUB_OUTPUT

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY }}:${{ steps.vars.outputs.tag }} .

    - name: Push Docker Image to ECR
      run: |
        docker push ${{ secrets.ECR_REPOSITORY }}:${{ steps.vars.outputs.tag }}

    - name: Output Image Tag
      run: echo "IMAGE_TAG=${{ steps.vars.outputs.tag }}" >> $GITHUB_ENV
