name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set Image Tag
        id: tag
        run: |
          echo "tag=strapi-${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=${{ secrets.ECR_REPO_URL }}:strapi-${{ github.sha }}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_TAG ./my-project
          docker push $IMAGE_TAG

      - name: Output and Save Image Tag
        run: echo "${{ steps.tag.outputs.tag }}" > ./image_tag.txt

      - name: Upload Image Tag as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: image_tag
          path: ./image_tag.txt
