name: CD - Terraform Deploy

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download image tag artifact
        uses: actions/download-artifact@v3
        with:
          name: image_tag
          path: .

      - name: Read Image Tag
        id: read_tag
        run: |
          IMAGE_TAG=$(cat image_tag.txt)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="image_tag=$IMAGE_TAG" -var="ecr_repo_url=${{ secrets.ECR_REPO_URL }}" -var="ssh_key_name=${{ secrets.SSH_KEY_NAME }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="image_tag=$IMAGE_TAG" -var="ecr_repo_url=${{ secrets.ECR_REPO_URL }}" -var="ssh_key_name=${{ secrets.SSH_KEY_NAME }}"
